name: Docs build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish documentation
        run: GITHUB_DEPLOY_KEY=${{ secrets.SSH_PRIVATE_KEY_BASE64 }} sbt docs/docusaurusPublishGhpages